// Code generated by Kitex v0.9.0. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	user "tiktok/kitex_gen/user"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetInfo": kitex.NewMethodInfo(
		getInfoHandler,
		newUserServiceGetInfoArgs,
		newUserServiceGetInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AvatarUpload": kitex.NewMethodInfo(
		avatarUploadHandler,
		newUserServiceAvatarUploadArgs,
		newUserServiceAvatarUploadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetMFAqrcode": kitex.NewMethodInfo(
		getMFAqrcodeHandler,
		newUserServiceGetMFAqrcodeArgs,
		newUserServiceGetMFAqrcodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MFABind": kitex.NewMethodInfo(
		mFABindHandler,
		newUserServiceMFABindArgs,
		newUserServiceMFABindResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.0",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRegisterArgs)
	realResult := result.(*user.UserServiceRegisterResult)
	success, err := handler.(user.UserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return user.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return user.NewUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLoginArgs)
	realResult := result.(*user.UserServiceLoginResult)
	success, err := handler.(user.UserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return user.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return user.NewUserServiceLoginResult()
}

func getInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetInfoArgs)
	realResult := result.(*user.UserServiceGetInfoResult)
	success, err := handler.(user.UserService).GetInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetInfoArgs() interface{} {
	return user.NewUserServiceGetInfoArgs()
}

func newUserServiceGetInfoResult() interface{} {
	return user.NewUserServiceGetInfoResult()
}

func avatarUploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceAvatarUploadArgs)
	realResult := result.(*user.UserServiceAvatarUploadResult)
	success, err := handler.(user.UserService).AvatarUpload(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceAvatarUploadArgs() interface{} {
	return user.NewUserServiceAvatarUploadArgs()
}

func newUserServiceAvatarUploadResult() interface{} {
	return user.NewUserServiceAvatarUploadResult()
}

func getMFAqrcodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetMFAqrcodeArgs)
	realResult := result.(*user.UserServiceGetMFAqrcodeResult)
	success, err := handler.(user.UserService).GetMFAqrcode(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetMFAqrcodeArgs() interface{} {
	return user.NewUserServiceGetMFAqrcodeArgs()
}

func newUserServiceGetMFAqrcodeResult() interface{} {
	return user.NewUserServiceGetMFAqrcodeResult()
}

func mFABindHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceMFABindArgs)
	realResult := result.(*user.UserServiceMFABindResult)
	success, err := handler.(user.UserService).MFABind(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceMFABindArgs() interface{} {
	return user.NewUserServiceMFABindArgs()
}

func newUserServiceMFABindResult() interface{} {
	return user.NewUserServiceMFABindResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *user.RegisterRequest) (r *user.RegisterResponse, err error) {
	var _args user.UserServiceRegisterArgs
	_args.Req = req
	var _result user.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *user.LoginRequest) (r *user.LoginResponse, err error) {
	var _args user.UserServiceLoginArgs
	_args.Req = req
	var _result user.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetInfo(ctx context.Context, req *user.InfoRequest) (r *user.InfoResponse, err error) {
	var _args user.UserServiceGetInfoArgs
	_args.Req = req
	var _result user.UserServiceGetInfoResult
	if err = p.c.Call(ctx, "GetInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AvatarUpload(ctx context.Context, req *user.AvatarUploadRequest) (r *user.AvatarUploadResponse, err error) {
	var _args user.UserServiceAvatarUploadArgs
	_args.Req = req
	var _result user.UserServiceAvatarUploadResult
	if err = p.c.Call(ctx, "AvatarUpload", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMFAqrcode(ctx context.Context, req *user.GetMFAqrcodeRequest) (r *user.GetMFAqrcodeResponse, err error) {
	var _args user.UserServiceGetMFAqrcodeArgs
	_args.Req = req
	var _result user.UserServiceGetMFAqrcodeResult
	if err = p.c.Call(ctx, "GetMFAqrcode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MFABind(ctx context.Context, req *user.MFABindRequest) (r *user.MFABindResponse, err error) {
	var _args user.UserServiceMFABindArgs
	_args.Req = req
	var _result user.UserServiceMFABindResult
	if err = p.c.Call(ctx, "MFABind", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
