// Code generated by hertz generator.

package common

import (
	"context"
	"fmt"
	common "tiktok/biz/model/common"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Ping .
// @router ping [GET]
func Ping(ctx context.Context, c *app.RequestContext) {
	var err error
	fmt.Println(err.Error())
	resp := new(common.BaseResp)

	c.JSON(consts.StatusOK, resp)
}
