// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"tiktok/config"
	"tiktok/dal/cache"
	"tiktok/dal/db"
	"tiktok/dal/es"
	"tiktok/pkg/util"
	"tiktok/service/ws"
)

func init() {
	util.InitLog()
	config.InitConfig()
	dao.InitMySQL()
	cache.LinkRedis()
	es.LinkEs()
	util.OssInit()
}
func main() {
	go ws.Manager.Start()
	h := server.Default(server.WithHostPorts("172.19.0.5:10001"),
		server.WithMaxRequestBodySize(419430400))
	register(h)
	h.Spin()
}
