// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"tiktok/config"
	"tiktok/dal/db"
	"tiktok/pkg/util"
)

func init() {
	util.InitLog()
	config.InitConfig()
	dao.InitMySQL()
	util.OssInit()
}
func main() {
	h := server.Default(server.WithHostPorts("localhost:10001"))
	register(h)
	h.Spin()
}
