// Code generated by hertz generator.

package video

import (
	"github.com/cloudwego/hertz/pkg/app"
	"tiktok/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tiktokMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _popularlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}
