// Code generated by hertz generator.

package social

import (
	"github.com/cloudwego/hertz/pkg/app"
	"tiktok/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tiktokMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fanslistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _followingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followlistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _friendsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendslistMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.JWT(),
	}
}
