// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/spf13/viper"
	"tiktok/cmd/api/biz/rpc"
	"tiktok/config"
	"tiktok/internal/utils"
)

func init() {
	//配置文件初始化
	viper.SetConfigName("config")
	viper.SetConfigType("yaml")
	viper.AddConfigPath("../../config")
	if err := viper.ReadInConfig(); err != nil {
		panic(err)
	}
	if err := viper.Unmarshal(&config.Config); err != nil {
		panic(err)
	}

	//logger
	utils.InitLog()

	rpc.Init()

}

func main() {
	h := server.Default(server.WithHostPorts("0.0.0.0:10001"))

	register(h)
	h.Spin()
}
