// Code generated by hertz generator. DO NOT EDIT.

package interaction

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	interaction "tiktok/biz/handler/interaction"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_tiktok := root.Group("/tiktok", _tiktokMw()...)
		{
			_comment := _tiktok.Group("/comment", _commentMw()...)
			_comment.DELETE("/delete", append(_deletecommentMw(), interaction.DeleteComment)...)
			_comment.GET("/list", append(_commentlistMw(), interaction.CommentList)...)
			_comment.POST("/publish", append(_commentpublishMw(), interaction.CommentPublish)...)
		}
		{
			_like := _tiktok.Group("/like", _likeMw()...)
			_like.POST("/action", append(_like0Mw(), interaction.Like)...)
			_like.GET("/list", append(_likelistMw(), interaction.LikeList)...)
		}
	}
}
