
system:
  domain: "tiktok"
  host: "172.19.0.4"
  port: "10001"

mysql:
  userName: "root"
  mysqlPassword: "123456"
  dbName: "tiktok"
  dbHost: "172.19.0.10"
  dbPort: "3306"

redis:
  redisHost: "172.19.0.2"
  redisPort: "6379"
  redisPassword: "123456"
  redisDbName: 2

oss:
  OSS_END_POINT: "*"
  OSS_ACCESS_KEY_ID: "*"
  OSS_ACCESS_KEY_SECRET: "*"
  OSS_BUCKET: "*"


es:
  esUserName: "elastic"
  esPassword: "elastic"
  esHost: "172.19.0.3"
  esPort: "9200"

rabbitmq:
  rabbitmqUserName: "smallpig"
  rabbitmqPassword: "123456"
