
system:
  domain: "tiktok"
  host: "127.0.0.1"
  port: "10001"

mysql:
  userName: "root"
  mysqlPassword: "123456"
  dbName: "tiktok"
  dbHost: "mysql"
  dbPort: "3306"

redis:
  redisHost: "redis"
  redisPort: "6379"
  redisPassword: "123456"
  redisDbName: 2

oss:
  OSS_END_POINT: "*"
  OSS_ACCESS_KEY_ID: "*"
  OSS_ACCESS_KEY_SECRET: "*"
  OSS_BUCKET: "*"


es:
  esUserName: "elastic"
  esPassword: "123456"
  esHost: "es"
  esPort: "9200"

rabbitmq:
  rabbitmqUserName: "root"
  rabbitmqPassword: "123456"
  rabbitmqHost: "rabbitmq"
  rabbitmqPort: "5672"
