// Code generated by hertz generator.

package common

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tiktokMw() []app.HandlerFunc {
	// your code...
	return nil
}
