// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	common "tiktok/biz/router/common"
	interaction "tiktok/biz/router/interaction"
	social "tiktok/biz/router/social"
	user "tiktok/biz/router/user"
	video "tiktok/biz/router/video"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	social.Register(r)

	interaction.Register(r)

	video.Register(r)

	common.Register(r)

	user.Register(r)
}
